/**
 * This class is generated by jOOQ
 */
package us.core_network.crust.io.dsl;


import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Table;
import org.jooq.impl.SchemaImpl;

import us.core_network.crust.io.dsl.tables.TClaim;
import us.core_network.crust.io.dsl.tables.TGroup;
import us.core_network.crust.io.dsl.tables.TGroupPlayer;
import us.core_network.crust.io.dsl.tables.TPlayer;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.0"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DefaultSchema extends SchemaImpl {

	private static final long serialVersionUID = -1493941086;

	/**
	 * The reference instance of <code></code>
	 */
	public static final DefaultSchema DEFAULT_SCHEMA = new DefaultSchema();

	/**
	 * No further instances allowed
	 */
	private DefaultSchema() {
		super("");
	}

	@Override
	public final List<Table<?>> getTables() {
		List result = new ArrayList();
		result.addAll(getTables0());
		return result;
	}

	private final List<Table<?>> getTables0() {
		return Arrays.<Table<?>>asList(
			TClaim.CLAIM,
			TGroup.GROUP,
			TGroupPlayer.GROUP_PLAYER,
			TPlayer.PLAYER);
	}
}
