/**
 * This class is generated by jOOQ
 */
package us.core_network.crust.io.dsl;


import javax.annotation.Generated;

import us.core_network.crust.io.dsl.tables.TClaim;
import us.core_network.crust.io.dsl.tables.TGroup;
import us.core_network.crust.io.dsl.tables.TGroupPlayer;
import us.core_network.crust.io.dsl.tables.TPlayer;


/**
 * Convenience access to all tables in 
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.0"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * The table claim
	 */
	public static final TClaim CLAIM = TClaim.CLAIM;

	/**
	 * The table group
	 */
	public static final TGroup GROUP = TGroup.GROUP;

	/**
	 * The table group_player
	 */
	public static final TGroupPlayer GROUP_PLAYER = TGroupPlayer.GROUP_PLAYER;

	/**
	 * The table player
	 */
	public static final TPlayer PLAYER = TPlayer.PLAYER;
}
