/**
 * This class is generated by jOOQ
 */
package us.core_network.crust.io.dsl.tables;


import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.TableImpl;

import us.core_network.crust.io.dsl.DefaultSchema;
import us.core_network.crust.io.dsl.tables.records.GroupPlayerRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.0"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TGroupPlayer extends TableImpl<GroupPlayerRecord> {

	private static final long serialVersionUID = -1120374576;

	/**
	 * The reference instance of <code>group_player</code>
	 */
	public static final TGroupPlayer GROUP_PLAYER = new TGroupPlayer();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<GroupPlayerRecord> getRecordType() {
		return GroupPlayerRecord.class;
	}

	/**
	 * The column <code>group_player.player</code>.
	 */
	public final TableField<GroupPlayerRecord, String> PLAYER = createField("player", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

	/**
	 * The column <code>group_player.group</code>.
	 */
	public final TableField<GroupPlayerRecord, Integer> GROUP = createField("group", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * Create a <code>group_player</code> table reference
	 */
	public TGroupPlayer() {
		this("group_player", null);
	}

	/**
	 * Create an aliased <code>group_player</code> table reference
	 */
	public TGroupPlayer(String alias) {
		this(alias, GROUP_PLAYER);
	}

	private TGroupPlayer(String alias, Table<GroupPlayerRecord> aliased) {
		this(alias, aliased, null);
	}

	private TGroupPlayer(String alias, Table<GroupPlayerRecord> aliased, Field<?>[] parameters) {
		super(alias, DefaultSchema.DEFAULT_SCHEMA, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TGroupPlayer as(String alias) {
		return new TGroupPlayer(alias, this);
	}

	/**
	 * Rename this table
	 */
	public TGroupPlayer rename(String name) {
		return new TGroupPlayer(name, null);
	}
}
