/**
 * This class is generated by jOOQ
 */
package us.core_network.crust.io.dsl.tables;


import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.TableImpl;

import us.core_network.crust.io.dsl.DefaultSchema;
import us.core_network.crust.io.dsl.tables.records.GroupRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.0"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TGroup extends TableImpl<GroupRecord> {

	private static final long serialVersionUID = 4511755;

	/**
	 * The reference instance of <code>group</code>
	 */
	public static final TGroup GROUP = new TGroup();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<GroupRecord> getRecordType() {
		return GroupRecord.class;
	}

	/**
	 * The column <code>group.id</code>.
	 */
	public final TableField<GroupRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>group.claim</code>.
	 */
	public final TableField<GroupRecord, Integer> CLAIM = createField("claim", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>group.name</code>.
	 */
	public final TableField<GroupRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.CLOB.nullable(false).defaulted(true), this, "");

	/**
	 * Create a <code>group</code> table reference
	 */
	public TGroup() {
		this("group", null);
	}

	/**
	 * Create an aliased <code>group</code> table reference
	 */
	public TGroup(String alias) {
		this(alias, GROUP);
	}

	private TGroup(String alias, Table<GroupRecord> aliased) {
		this(alias, aliased, null);
	}

	private TGroup(String alias, Table<GroupRecord> aliased, Field<?>[] parameters) {
		super(alias, DefaultSchema.DEFAULT_SCHEMA, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TGroup as(String alias) {
		return new TGroup(alias, this);
	}

	/**
	 * Rename this table
	 */
	public TGroup rename(String name) {
		return new TGroup(name, null);
	}
}
