/**
 * This class is generated by jOOQ
 */
package us.core_network.crust.io.dsl.tables.records;


import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.TableRecordImpl;

import us.core_network.crust.io.dsl.tables.TGroupPlayer;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.0"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GroupPlayerRecord extends TableRecordImpl<GroupPlayerRecord> implements Record2<String, Integer> {

	private static final long serialVersionUID = 1488848198;

	/**
	 * Setter for <code>group_player.player</code>.
	 */
	public void setPlayer(String value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>group_player.player</code>.
	 */
	public String getPlayer() {
		return (String) getValue(0);
	}

	/**
	 * Setter for <code>group_player.group</code>.
	 */
	public void setGroup(Integer value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>group_player.group</code>.
	 */
	public Integer getGroup() {
		return (Integer) getValue(1);
	}

	// -------------------------------------------------------------------------
	// Record2 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row2<String, Integer> fieldsRow() {
		return (Row2) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row2<String, Integer> valuesRow() {
		return (Row2) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field1() {
		return TGroupPlayer.GROUP_PLAYER.PLAYER;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field2() {
		return TGroupPlayer.GROUP_PLAYER.GROUP;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value1() {
		return getPlayer();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value2() {
		return getGroup();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public GroupPlayerRecord value1(String value) {
		setPlayer(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public GroupPlayerRecord value2(Integer value) {
		setGroup(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public GroupPlayerRecord values(String value1, Integer value2) {
		value1(value1);
		value2(value2);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached GroupPlayerRecord
	 */
	public GroupPlayerRecord() {
		super(TGroupPlayer.GROUP_PLAYER);
	}

	/**
	 * Create a detached, initialised GroupPlayerRecord
	 */
	public GroupPlayerRecord(String player, Integer group) {
		super(TGroupPlayer.GROUP_PLAYER);

		setValue(0, player);
		setValue(1, group);
	}
}
