/**
 * This class is generated by jOOQ
 */
package us.core_network.crust.io.dsl.tables.records;


import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.TableRecordImpl;

import us.core_network.crust.io.dsl.tables.TGroup;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.0"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GroupRecord extends TableRecordImpl<GroupRecord> implements Record3<Integer, Integer, String> {

	private static final long serialVersionUID = -1727724496;

	/**
	 * Setter for <code>group.id</code>.
	 */
	public void setId(Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>group.id</code>.
	 */
	public Integer getId() {
		return (Integer) getValue(0);
	}

	/**
	 * Setter for <code>group.claim</code>.
	 */
	public void setClaim(Integer value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>group.claim</code>.
	 */
	public Integer getClaim() {
		return (Integer) getValue(1);
	}

	/**
	 * Setter for <code>group.name</code>.
	 */
	public void setName(String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>group.name</code>.
	 */
	public String getName() {
		return (String) getValue(2);
	}

	// -------------------------------------------------------------------------
	// Record3 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row3<Integer, Integer, String> fieldsRow() {
		return (Row3) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row3<Integer, Integer, String> valuesRow() {
		return (Row3) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field1() {
		return TGroup.GROUP.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field2() {
		return TGroup.GROUP.CLAIM;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field3() {
		return TGroup.GROUP.NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value2() {
		return getClaim();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value3() {
		return getName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public GroupRecord value1(Integer value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public GroupRecord value2(Integer value) {
		setClaim(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public GroupRecord value3(String value) {
		setName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public GroupRecord values(Integer value1, Integer value2, String value3) {
		value1(value1);
		value2(value2);
		value3(value3);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached GroupRecord
	 */
	public GroupRecord() {
		super(TGroup.GROUP);
	}

	/**
	 * Create a detached, initialised GroupRecord
	 */
	public GroupRecord(Integer id, Integer claim, String name) {
		super(TGroup.GROUP);

		setValue(0, id);
		setValue(1, claim);
		setValue(2, name);
	}
}
